import "MindPalace-sigma.js/src/renderers/sigma.renderers.svg.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.utils.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.nodes.def.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.edges.def.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.edges.curve.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.labels.def.js"
import "MindPalace-sigma.js/src/renderers/svg/sigma.svg.hovers.def.js"
